# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'Repository Categories'
description: 'This action creates a list of categories from the repositories in a GitHub organization.'
author: 'Mqxx'
branding:
  icon: 'grid'
  color: 'green'

inputs:
  token:
    description: 'The GitHub token to use.'
    required: true

  config-file:
    description: 'The configuration file to use.'
    required: false

  organization-name:
    description: |
      If already specified in the configuration file, this will be omitted.

      The name of the organization in which to search the repositories for the categories.
    required: false
    default: '${{ github.event.repository.owner.name }}'

  only-public-repositories:
    description: |
      If already specified in the configuration file, this will be omitted.

      Query only public repositories. Private repositories will be ignored.
    required: false
    default: 'true'

  template-files:
    description: |
      If already specified in the configuration file, this will be omitted.

      Template files to use for the categories.
    required: false
    default: |
      readme: './.github/categories/templates/readme.md'
      category: './.github/categories/templates/category.md'
      repository: './.github/categories/templates/repository.md'

  label-search-pattern:
    description: |
      If already specified in the configuration file, this will be omitted.

      The category regex search pattern to use when searching for category labels in the repositories.
      Specify the categories as comma separated values in the label description.
    required: false
    default: 'category'

  repository-blacklist:
    description: |
      If already specified in the configuration file, this will be omitted.

      List of repository names to blacklist.
    required: false

  categories:
    description: |
      If already specified in the configuration file, this will be omitted.

      The category mapping. Can either be a YAML mapping or a path to a JSON file.
      Use an empty key for the default category.

      Example:
        "": "No Category"
        "category_1": "Category 1"
    required: false
    default: |
      "": "No Category"

outputs:
  generated-readme-text:
    description: 'The generated README file with the categories.'

  categories-changed:
    description: 'If a category was added/changed/removed.'

runs:
  using: 'docker'
  image: 'docker://denoland/deno:latest'
  entrypoint: 'deno'
  args:
    - 'run'
    - '-A'
    - './src/index.ts'
